import java.util.List;
import java.sql.*;

import domain.*;
import repositories.*;
import repositoriesImpl.*;
import unitofwork.IUnitOfWork;
import unitofwork.UnitOfWork;
public class Main {

	public static void main(String[] args) {
		
		String url="jdbc:hsqldb:hsql://localhost/workdb";
		
		User ddobek = new User();
		ddobek.setLogin("DamianDobek");
		ddobek.setPassword("admin1");
		
		try {
			
			Connection connection = DriverManager.getConnection(url);
			IUnitOfWork uow = new UnitOfWork(connection);
			/*
			String createTableSql = 
					"CREATE TABLE users("
					+ "id int GENERATED BY DEFAULT AS IDENTITY,"
					+ "login VARECHAR(20),"
					+ "password VARCHAR(20),"
					+ ")";
			Statement createTable = connection.createStatement();
			createTable.executeUpdate(createTableSql);
			*/
			
			IRepositoryCatalog catalog = new RepositoryCatalog(connection, uow);
			
			catalog.getUsers().save(ddobek);
			List<User> usersFromDb = catalog.getUsers().getAll();
			
			for(User userFromDb: usersFromDb)
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			User a = catalog.getUsers().get(2);
			a.setPassword("admin2");
			catalog.getUsers().update(a);
			catalog.getUsers().delete(usersFromDb.get(0));
			
			for(User userFromDb: catalog.getUsers().getAll())
				System.out.println(userFromDb.getId()+" "+userFromDb.getLogin()+" "+userFromDb.getPassword());
			
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
		
		System.out.println("koniec");
	}

}
